services:
    Enhavo\Bundle\DoctrineExtensionBundle\Command\DebugDoctrineMappingInfoCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: console.command }
