services:
    Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EntityResolverInterface:
        alias: Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\ChainResolver

    Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\ChainResolver:
        calls:
            - [addResolver, ['@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EnhavoResourceResolver', 200]]
            - [addResolver, ['@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\ClassNameResolver', 100]]

    Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EnhavoResourceResolver:
        arguments:
            - '%enhavo_resource.resources%'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'

    Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\ClassNameResolver:
        arguments:
            - '@doctrine.orm.entity_manager'
